server:
  port: 8000 #eureka端口号

spring:
  application:
    name: eureka-service2

eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false #是否将自己注册到注册中心
    #fetch-registry: false #是否从eureka获取注册信息
    service-url: #配置暴露给eureka Client的请求地址
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
